### ISSUE TITLE
Standardise index.css to include all font faces

### ISSUE THREAD

**Issue by ed-wright** [fontsource/fontsource#100]
**Is your feature request related to a problem? Please describe.**
Please see issue #99, this issue is a continuation of the discussion there into a seperate feature request so that pull request can be closed.

**Describe the solution you'd like**
Would you consider the idea of changing the index.css? Instead of only containing the 400 font replacing it with all available font-faces for that particular font. This would avoid any breaking change, and would standardise the index.css across all fonts. This obviously would increase import size but users looking to decrease package size will look through the docs and implement one of the subset css files. This would allow users that are new to the project to get started faster and users with size constraints to use the project to its full potential. IMHO (ease of use through standardisation) >> (small code size)

**Describe alternatives you've considered**
Issue #99 is a manual implementation for a single font but only implements weight 300. As discussed this need to be fixed programmatically rather than manual file writing.

**Additional context**
N/A. I am willing to help with this and other issues if @DecliningLotus is happy. Admittedly JS is not my strongpoint as I am primarilly a Python and C++ programmer but willing to help!

**Comment by ayuhito** [comment]
I appreciate the idea, but unfortunately, I had done this in the past until we pushed the [unicode-range update](https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md#30x).

The reason why this isn't possible is that fonts for very large languages like [Noto Sans JP](https://github.com/fontsource/fontsource/blob/master/packages/noto-sans-jp/400.css) or [Noto Sans TC](https://github.com/fontsource/fontsource/blob/master/packages/noto-sans-tc/400.css) have many small unicode-range subsets to reduce filesize users would need to download upon visiting a website.

If we aggregate all weights into one CSS file, we would end up with a 3MB+ index.css files for these types of fonts which is extremely counter-intuitive for the whole purpose of this project.

Does that address your suggestion or did you mean for something else?

**Comment by ed-wright** [comment]
You have addressed my suggestion.

To change the idea slightly, would it be better to instead to implement #89 and remove the idea of index.css entirely. You could first put a deprecation notice so that users are aware of the change. Along with this it would be great if a user could interact with a frontend ui to select what fonts and what font weights that they want and the code to add to their projects is autogenerated.

**Comment by ayuhito** [comment]
That is probably the best way forward. It'll just be part of a major update that takes care of all breaking changes.

I'll close this for now.
