### ISSUE TITLE
NPM packages out of date

### ISSUE THREAD

**Issue by mshuster** [fontsource/fontsource#104]
`fontsource-` namespaced packages have a wide range of published versions on NPM, most ranging from `3.0.0`-`3.0.11`. I've yet to see published versions in the `3.1.*` range.

I first noticed this attempting to install `fontsource-inter@3.1.2`, but the most recently published version is `3.0.5`, from four months ago.

I'm eager to see the `3.1.2` package versions since the (hopefully) contain the variable binaries (many, many thanks for those btw). 🙏

**Comment by ayuhito** [comment]
Hey, sorry about that. Lerna is an absolute pain to get working and whilst the tags have been getting pushed, I failed to get the publish cycle for 3.1.x out last night and called it a day. 

Happens every single minor/major publish with a new different error to figure out. 😕 I'll close #30 when the packages are properly published.
