### ISSUE TITLE
Some binaries missing file extensions

### ISSUE THREAD

**Issue by mshuster** [fontsource/fontsource#105]
e.g. https://github.com/fontsource/fontsource/blob/master/packages/inter/files/inter-latin-variable-full-oblique

I assume this is also meant to be `woff2` but it was published without a file extension.

**Comment by ayuhito** [comment]
Should be a bug unique to the SLNT axes, or more specifically a function related to setting the download file paths of binaries that wasn't ready to handle the SLNT format. To my knowledge, it should only be Recursive and Inter that should be affected if my hypothesis is correct. 

Thanks for the notice! I'll look into resolving that soon.

**Comment by ayuhito** [comment]
There's an upstream bug in [fontsource/google-font-metadata](https://github.com/fontsource/google-font-metadata) which seems to be affecting these two binaries too.

**Comment by ayuhito** [comment]
Fixed with latest update, packages have been published. Thanks for the issue.
