### ISSUE TITLE
Comic Mono

### ISSUE THREAD

**Issue by dtinth** [fontsource/fontsource#113]
**Font Name**
Comic Mono

**Link to font source**
https://github.com/dtinth/comic-mono-font

**Link to font license**
https://github.com/dtinth/comic-mono-font/blob/master/LICENSE
MIT

**Additional context**
[Comic Mono](https://dtinth.github.io/comic-mono-font/) is a fork of [Comic Shanns](https://github.com/dtinth/comic-mono-font) with updated metrics.

<a href="https://dtinth.github.io/comic-mono-font/"><img src="https://repository-images.githubusercontent.com/164606802/cd83d680-894c-11e9-83f7-c353c70df1cb" alt="Screenshot"></a>

**Comment by ayuhito** [comment]
Just dropping a note that this might take a while since I'm working on #92 at the moment which directly affects the addition of new fonts.

**Comment by dtinth** [comment]
@DecliningLotus Thanks for the update, and thanks for maintaining this project 😄

**Comment by dtinth** [comment]
Thanks! ❤️
