### ISSUE TITLE
documentation request: how to force load of static version of font that can be variable (if possible)

### ISSUE THREAD

**Issue by jebeck** [fontsource/fontsource#114]
Some text on a website of mine with fontsource-exo-2 broke recently due to [this rendering bug](https://github.com/rsms/inter/issues/292). The only mitigation given in that issue is not using a variable font, but it's not clear to me how to load the static version, if that's even possible. Some clarity around this (even just a sentence or two) in the docs would be great!

**Comment by ayuhito** [comment]
Hey @jebeck,

I'm fairly sure static means to use the regular font import and not the variable variant.

This has already been discussed in NDISCOVER/Exo-2.0#11 and it seems that Fontsource does seem to have it working.

Does that clarify your concerns? I'm not sure if it's necessary to amend the documentation for this specifically.

**Comment by jebeck** [comment]
> Hey @jebeck,
> 
> I'm fairly sure static means to use the regular font import and not the variable variant.

Yes, I understood this. 

> This has already been discussed in [NDISCOVER/Exo-2.0#11](https://github.com/NDISCOVER/Exo-2.0/issues/11) and it seems that Fontsource does seem to have it working.
> 
> Does that clarify your concerns? I'm not sure if it's necessary to amend the documentation for this specifically.

No, I still don't understand _how_ to make fontsource use the regular import instead of the variable (if that's even possible), and I think that would be a good addition to the docs if it is possible. In my case, I just ended up changing the problematic font styling since I couldn't figure it out, so it doesn't matter to me so much anymore. Not an ideal solution, but it wasn't worth the time it was sucking up trying to figure it out.

**Comment by ayuhito** [comment]
> No, I still don't understand _how_ to make fontsource use the regular import instead of the variable (if that's even possible).

What I meant by that is to use the non-variable fonts.

E.g. 'import @fontsource/fontname/400.css'
