### ISSUE TITLE
Font request Noto Mono

### ISSUE THREAD

**Issue by mauriciabad** [fontsource/fontsource#125]
**Font Name**
Noto Mono

**Link to font source**
Homepage: https://www.google.com/get/noto/#mono-mono

Repository: https://github.com/googlefonts/noto-fonts

Font files inside the repository: https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansMono

**Link to font license**
https://github.com/googlefonts/noto-fonts/blob/master/LICENSE 
It's a SIL Open Font License

**Additional context**
The Noto font is already available in Sans and Serif, but not Monospace. There are very few monospace fonts available, this would be a great addition.

**Comment by ayuhito** [comment]
@mauriciabad, do you think we should support [Noto Mono](https://www.google.com/get/noto/#mono-mono) or [Noto Sans Mono](https://www.google.com/get/noto/#sans-mono)?

They seem identical, except Google seems to continue updating the latter variant and it has a wider range of weights. I don't think it's necessary to add Noto Mono then. Or is there a difference?

**Comment by ayuhito** [comment]
Although a further look into it shows that Noto Mono is significantly smaller than Noto Sans Mono since it supports far fewer languages. We don't necessarily have a subsetting procedure set for non-Google Fonts to exactly subset these fonts, so there may be a conflict of interest.

**Comment by mauriciabad** [comment]
@DecliningLotus I wasn't aware that they where two different fonts. I don't have any preference, so you can chose which one would be better to implement.

**Comment by ayuhito** [comment]
Sorry for the delay. I've been a bit busy.

I've gone ahead with the former Noto Mono font as it is far more practical in terms of serving over the web. The package should be published by tomorrow.
