### ISSUE TITLE
Font Request: PlusJakartaSans

### ISSUE THREAD

**Issue by vzrenggamani** [fontsource/fontsource#132]
**Font Name**
PlusJakarta Sans

**Link to font source**
https://github.com/tokotype/PlusJakartaSans

**Link to font license**
https://github.com/tokotype/PlusJakartaSans/blob/master/LICENSE.md

**Additional context**
designed by https://tokotype.com

**Comment by ayuhito** [comment]
Resolved in #135. Should be published to NPM by tomorrow. Thanks for the issue!
