### ISSUE TITLE
Add CommonJS example for the use in gatsby-browser.js

### ISSUE THREAD

**Issue by kuworking** [fontsource/fontsource#151]
Since `gatsby-browser.js` requires `CommonJS`, it would be useful to add this example in the docs

A real example would be myself, now that I have to switch back from ES6 to CommonJS due to a deep&obscure bug in gatsby, the last part that I need to fix is how to insert `import '@fontsource/pontano-sans'` in  `gatsby-browser.js` and in `CommonJS`

EDIT: just like this

```js
require('@fontsource/pontano-sans')
require('@fontsource/thasadith')
```

**Comment by ayuhito** [comment]
I'll take this into consideration when rewriting for #145. Thanks for the issue!
