### ISSUE TITLE
Font Request: Carlito

### ISSUE THREAD

**Issue by ben-demotic** [fontsource/fontsource#157]
**Font Name**
Carlito

**Link to font source**
https://fontlibrary.org/en/font/carlito
https://fontlibrary.org/assets/downloads/carlito/8b80255a5a467b7af83add3ceec73209/carlito.zip

**Link to font license**
http://scripts.sil.org/OFL

**Additional context**
This is an Open Source alternative to Microsoft Calibri.

Thank you.

**Comment by ayuhito** [comment]
google/fonts#1441 proves to be an interesting read regarding this font and its future. It should be adopted by Google soon, and Fontsource will automatically replace the files with the Google versions whenever they go about uploading it.

In the meantime, I'll add our own version as a stopgap solution.
