### ISSUE TITLE
Mixins generates wrong font file name when unicode-range subset is number

### ISSUE THREAD

**Issue by divinespear** [fontsource/fontsource#166]
**Describe the bug**
mixins generates wrong font file name so error thrown while building.
It affects every fonts that `$unicodeMap` is mapped by number, especially CJK fonts (`noto-sans-*`, `noto-serif-*`, ...)

My environment is:
 * vue 2.6.12
 * webpack 4.46.0
 * sass (dart-sass) 1.32.6

**To Reproduce**

build with this source
```scss
@import '~@fontsource/noto-sans-kr/scss/mixins';

@include fontFace($weight: 300);
@include fontFace($weight: 400);
@include fontFace($weight: 500);
```

throws error below
```
Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve '@fontsource/noto-sans-kr/files/noto-sans-kr-[0]-300-normal.woff2' in '/workspace/packages/app-user/src'
```

actual file name should be `noto-sans-kr-0-300-normal.woff2`.

**Expected behavior**

change index like `[0]` to just numeric like `0` or `'0'` to work.

**Comment by ayuhito** [comment]
Ah, we just need to strip the square brackets when inputting the variables into the Lodash template (google and generic builders). Should be a very simple fix.

Appreciate the issue.
