### ISSUE TITLE
Font Request: Droid Serif

### ISSUE THREAD

**Issue by maimArt** [fontsource/fontsource#174]
**Font Name**
Droid Serif

**Link to font source**
https://www.fontsquirrel.com/fonts/droid-serif

**Link to font license**
https://www.fontsquirrel.com/license/droid-serif

**Additional context**
Also found it on https://fonts.google.com/?query=droid+serif ,but its not imported in fontsource. Maybe because when following the links to https://www.fonts.com/de/font/ascender/droid-serif/licenses it looks like it is licensed?

**Comment by ayuhito** [comment]
It is a paid licensed font that isn't open source, so no, we cannot integrate this font with Fontsource.

Thanks for the issue!

**Comment by maimArt** [comment]
I feared that could be the case. But thank you very much for having a look on this.
