### ISSUE TITLE
Provide more font weights on cascadia code

### ISSUE THREAD

**Issue by 3xau1o** [fontsource/fontsource#175]
provide other font weights than 400 to cascadia-code

https://www.npmjs.com/package/@fontsource/cascadia-code/v/4.2.0 

![image](https://user-images.githubusercontent.com/19735362/112409791-5eb96e00-8cd7-11eb-8746-8a6cf88047c9.png)

**Comment by ayuhito** [comment]
Actually, it seems like I will need to deprecate Cascadia Code due to the RFN in their license. Refer to microsoft/cascadia-code#56.
