### ISSUE TITLE
@fontsource/lato is missing font weight 500 and 600

### ISSUE THREAD

**Issue by lexmes** [fontsource/fontsource#182]
**Describe the bug**
In the @fontsource/lato README it states that there should be a 500 and 600 font weight version of the lato font. But when you actually install the package via npm the weights are missing.

**To Reproduce**

1. Go to https://github.com/fontsource/fontsource/tree/main/packages/lato
2. Scroll to "Installation" section
3. In the parahraph about mixins look for a code section
    ```
    @include fontFace(
      $weight: 500,
      $display: fallback,
      $fontDir: "~@fontsource/lato/files"
    );
    ```
4. Install `@fontsource/lato` in your project
5. Try to include the snippet @fontFace snippet with a 500 weight
6. Look into the console which should show an error that the font weight 500 font is missing

**Expected behavior**
The README shouldn't state that there is a weight 500 and 600 version or the font should. See https://fonts.google.com/specimen/Lato?query=lato#standard-styles

**Screenshots**

**Additional context**
`@fontsource/lato` 4.2.2

**Comment by lexmes** [comment]
Ok, my fault. It seems google removed the 500 and 600 versions of the font. I'm closing this issue.

**Comment by ayuhito** [comment]
The issue with this is that these READMEs are auto-generated and have values just to roughly guide users how to install this package. Below all that is a disclaimer stating the following:

> These examples may not reflect actual compatibility. Please refer below.
> 
> Supported variables:
> 
> Weights: [100,300,400,700,900]
Styles: [italic,normal]

I don't feel it's necessary to add additional logic to the README templates we have, and it would be a bit complicated to implement such as we'd need to account for certain fonts that only have weight 400 etc.

Also, work on #145 would probably resolve any future confusion regarding this matter.

**Comment by ayuhito** [comment]
Closing due to reasons above.
