### ISSUE TITLE
Font Request: Atkinson Hyperlegible

### ISSUE THREAD

**Issue by nik27** [fontsource/fontsource#202]
**Font Name**
Atkinson Hyperlegible

**Link to font source**
[Font source](https://brailleinstitute.org/freefont)

**Link to font license**
[Licence](https://www.brailleinstitute.org/wp-content/uploads/2020/11/Atkinson-Hyperlegible-Font-License-2020-1104.pdf)

**Additional context**
Great font for low vision readers created by Braille Institute.

**Comment by ayuhito** [comment]
Thanks for the issue! The font has been added. You should see it posted onto NPM by the end of today.
