### ISSUE TITLE
Unable to import font

### ISSUE THREAD

**Issue by anubra266** [fontsource/fontsource#212]
**Describe the bug**
I'm trying to import a font in a Laravel project, 
```js
import "@fontsource/poppins";
```
and I'm getting
```js
GEThttp://127.0.0.1:8000/node_modules/@fontsource/poppins/files/poppins-latin-400-normal.woff2
[HTTP/1.0 404 Not Found 84ms]

downloadable font: download failed (font-family: "Poppins" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: http://127.0.0.1:8000/node_modules/@fontsource/poppins/files/poppins-latin-400-normal.woff2
GEThttp://127.0.0.1:8000/node_modules/@fontsource/poppins/files/poppins-all-400-normal.woff
[HTTP/1.0 404 Not Found 29ms]

downloadable font: download failed (font-family: "Poppins" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: http://127.0.0.1:8000/node_modules/@fontsource/poppins/files/poppins-all-400-normal.woff
```
![image](https://user-images.githubusercontent.com/30869823/117556713-c0555200-b063-11eb-8fbe-123ad8bfc68a.png)

I don't know if that's how fontsource generally works, but it's trying to import through url, not directly from the project's filesystem, and node modules is not available on the project's url, soimport fails.

**Comment by ayuhito** [comment]
Possible duplicate of #163?

You need to use a bundler like Webpack, which processes everything beforehand to bundle the Fontsource files into something consumable by the browser.

If it's Laravel Mix, I think they can create a fix if an issue is created upstream. They just need to support CSS imports - I've seen other bundlers like Snowpack add support just for this use case. Pure Laravel will never work I believe.

**Comment by anubra266** [comment]
It's not pure laravel, I'm using react with vitejs, for my frontend.

**Comment by ayuhito** [comment]
I'd look into creating an upstream issue at Vite then. This isn't something I can fix on my end and I don't really have much experience with Vite to offer any advice for a workaround.

Some other bundlers to Webpack don't resolve the imports and URL references within a CSS file properly, which leads to this.

Similar to snowpackjs/snowpack#2885

**Comment by anubra266** [comment]
OK...THANKS
