### ISSUE TITLE
Vercel/Nextjs for some reason removes the fonts when using Webpack 5

### ISSUE THREAD

**Issue by italodeandra** [fontsource/fontsource#215]
**Describe the bug**
The fonts are not downloaded (or are being removed during build) when using Next.js with Webpack deployed to Vercel.

**To Reproduce**

1. Go to https://fontsource.org/
2. Its using the `Arial` font instead of `Inter` font.

**Expected behavior**
It should be using the `Inter` font.

**Screenshots**
![image](https://user-images.githubusercontent.com/19225266/117673651-40d29a80-b1ab-11eb-9c86-3a8d6e7fb696.png)

**Additional context**
I'm actually reporting this bug because my application also has this problem and I can only "fix" it by rolling back to Webpack 4. And it was only a coincidence that I checked the doc website and saw that you also use Webpack 5 deployed on Vercel and had the same problem.

**Comment by ayuhito** [comment]
Thank you for reporting this, I actually didn't realise! I identified the error relating to how I switched the website to use variable fonts, but that also requires the CSS font-family attribute to be referred to as 'InterVariable' and 'RalewayVariable'.

I think it may be good to highlight the font name change in https://fontsource.org/docs/variable-fonts since even I forgot about it and it's obscurely mentioned at the bottom of the page.

Hopefully, #216 actually does fix it.

**Comment by ayuhito** [comment]
Interesting. The fonts show correctly in development mode now, but when built, it fails with the font files showing 404 errors. 
![image](https://user-images.githubusercontent.com/38220115/117680127-8e560400-b1b9-11eb-9d2f-1c7db4d81ad3.png)

The URL they are trying to access according to this [CSS file](https://fontsource-git-docs-fix-docs-font-loading-fontsource.vercel.app/_next/static/css/3332d4a458e51610045c.css) doesn't go anywhere. The media folder itself that they are referencing doesn't even exist. This media folder, however, is there in development mode within the .next folder in my local environment. 

I'll have time to look into this more tomorrow, but I'm somewhat unsure whether this is isolated to Next (this most likely from what I've seen), Vercel or Webpack so far, so any additional help to investigate would be appreciated!

**Comment by italodeandra** [comment]
You investigation was the same I did. The media files from the fonts don't go to the Vercel source (if you check on the deploy). I'm too not sure who's the fault here, but if you want to have a workaround for now just use Webpack 4 instead of 5.

I'll contact Vercel about it. Because I couldn't find any other reference around.

**Comment by ayuhito** [comment]
Just to reinforce the conclusion, I deleted the .next folder and rebuilt the whole site locally with Webpack 5 enabled. The media folder was there.

![image](https://user-images.githubusercontent.com/38220115/117804860-f4499680-b260-11eb-8977-015d5daf8a60.png)


I'll also look into contacting Vercel since it seems like it may be something on their end.

**Comment by chr-ge** [comment]
I am also getting this error on my live Next.js site hosted on Vercel but it works fine in dev.

**Comment by ayuhito** [comment]
@italodeandra, @chr-ge - I'm trying to make a minimum reproducible build for Vercel to look at but I'm somewhat stumped on what's causing this now.

https://github.com/fontsource/fontsource-vercel-reproduction : https://fontsource-vercel-reproduction.vercel.app/
https://github.com/DecliningLotus/next-lotus-starter : https://next-lotus-starter.vercel.app/

Both of the above builds are very basic installations of Next.js with Webpack 5 enabled. The first is a direct create-next-app build with no additional packages. The second uses the Chakra UI library which uses emotion for CSS-in-JS, similar to the Fontsource website.

Both of them render their fonts correctly on Vercel. Do our projects have any other similarities that could lead to finding the cause? Are you guys able to create a minimal reproducible repo?

**Comment by italodeandra** [comment]
I stole your reproduction repo and tried some things.

The fonts were gone as soon as I changed the code to TypeScript:

https://github.com/italodeandra/fontsource-vercel-reproduction : https://fontsource-vercel-reproduction-psi.vercel.app/

**Comment by chr-ge** [comment]
That might be it since I'm am also using Typescript along with Webpack 5, ChakraUI. [website-repo](https://github.com/chr-ge/chr-ge.com)

**Comment by italodeandra** [comment]
![image](https://user-images.githubusercontent.com/19225266/117985987-81f8b500-b339-11eb-95a8-0c335254d68d.png)

Locally the folder `media` is generated with the fonts. But it's missing from Vercel's.

**Comment by ayuhito** [comment]
@italodeandra, awesome! I'll update my reproduction with Typescript then since I'm giving Vercel access to my account to investigate the deployment deeper.

**Comment by ayuhito** [comment]
I am very confused about what's going on. I'm writing this to document so far what I have experienced for Vercel to read over.

My first commit to adding Typescript led to the fonts actually rendering: https://fontsource-vercel-reproduction-9tg6u4me2-fontsource.vercel.app/

After committing a few more times trying to figure out the cause, it stopped working - it is pretty much the exact same code as my first implementation of Typescript: https://fontsource-vercel-reproduction.vercel.app/

There's a possibility this is due to Vercel using previous caches of the next folder, leading to the series of successful builds. But I'll leave that for those at Vercel to validate.

I've updated Vercel with all the new reproductions and info. Thank you all.

**Comment by italodeandra** [comment]
> After committing a few more times trying to figure out the cause, it stopped working - it is pretty much the exact same code as my first implementation of Typescript: https://fontsource-vercel-reproduction.vercel.app/

This happened with me too. After the deploy with TypeScript was complete, my first browsing to the page the fonts were there. But as a reflex I have, I hit Ctrl + F5 and then the fonts were gone. So in my case it was my own browser's cache.

> I'll leave that for those at Vercel to validate.

Thanks!

**Comment by mcsdevv** [comment]
Hi all, Matthew from Vercel here, I'm sorry for the trouble you're experiencing with this - we'll be looking into this hopefully next week.

I also wanted to say thank you, especially to @DecliningLotus, for putting together such a great thread and reproduction steps, this is a massive help to us and greatly appreciated.

**Comment by ayuhito** [comment]
@italodeandra, @chr-ge - Could you try redeploying your projects (without build cache) and seeing if the problem persists?

**Comment by rstacruz** [comment]
I'm experiencing this too. While this is being investigated, the workaround I do is to redeploy without a build cache.

A redeploy from the Vercel UI should already have the build cache turned off (noticed the unchecked checkbox):

> ![image](https://user-images.githubusercontent.com/74385/118907671-4bd3ba80-b963-11eb-84b7-0096ce4ee8f0.png)

The CLI can also be used with the `-f` parameter to force deploying without a cache:

```
npx vercel --prod -f
```

**Comment by mcsdevv** [comment]
Hi all, this has been resolved in [this PR](https://github.com/vercel/next.js/pull/24573) and made available as of the latest Next.js stable - 10.2.2.

Please let us know should you encounter any further issues.

**Comment by ayuhito** [comment]
@mcsdevv, thank you so much to you and your team for investigating the issue! Big thanks to everyone else in this issue for helping out too!

I'll be closing this issue unless we experience this again. The standard FAQ response should be to update to Next 10.2.2 and redeploy without the build cache for this specific issue.

**Comment by whimpe** [comment]
Hello comunity, I know this issue is closed. But we are experiencing the exact same problem using Next@12.0, Is it possible that this issue has returned?

**Comment by italodeandra** [comment]
@whimpe Could be. This is related of how the compiler works, and they just refactor 100% of the compiler (switching to rust).

@mcsdevv Are you aware of anything related to this? Can you him with that? Where can he report it?

**Comment by ayuhito** [comment]
Are others able to reproduce this? If we could get a minimum reproducible build, it would help out the Vercel team to look into the matter.

**Comment by rickyzhangca** [comment]
> I'm experiencing this too. While this is being investigated, the workaround I do is to redeploy without a build cache.
> 
> A redeploy from the Vercel UI should already have the build cache turned off (noticed the unchecked checkbox):
> 
> > ![image](https://user-images.githubusercontent.com/74385/118907671-4bd3ba80-b963-11eb-84b7-0096ce4ee8f0.png)
> 
> The CLI can also be used with the `-f` parameter to force deploying without a cache:
> 
> ```
> npx vercel --prod -f
> ```

My deployment is missing the fonts too (the same build command running locally works just fine). It's still missing the fonts after redeploying without cache. Not sure why.

**Comment by mcsdevv** [comment]
> @whimpe Could be. This is related of how the compiler works, and they just refactor 100% of the compiler (switching to rust).
> 
> @mcsdevv Are you aware of anything related to this? Can you him with that? Where can he report it?

No reports thus far, if a minimal reproduction is provided at vercel.com/support/request, we'll happily take a look! I'd strongly recommend referencing this thread also.

**Comment by frontendwizard** [comment]
I just bumped on this issue using Chakra UI + Typescript and fontsource. I'll try to replicate on a minimal setup

**Comment by frontendwizard** [comment]
a `npx vercel --prod -f` did fix the issue, it only happened on the first deploy I made on this project.

**Comment by frontendwizard** [comment]
False alarm, I used variable fonts but on my theme setup I did not used the `Variable` suffix on the name. That still works on Chrome on desktop, but doesn't work elsewhere. Once I used the correct font name, everything worked, meaning the font was indeed loading.

**Comment by ayuhito** [comment]
@whimpe, is this issue still persisting? If so, are you able to reproduce it?

**Comment by Ensemble-Studio** [comment]
I thought I had the same issue, my fonts didnt load but showed up on localhost.  Turns out I should have NOT include the /public folders in the path refering to the fonts in my css, as Vercel will see your public folder as your root folder. Hope this helps anyone who is struggling with the same problem!
