### ISSUE TITLE
Font Request: Flow

### ISSUE THREAD

**Issue by gomflo** [fontsource/fontsource#218]
**Font Name**
Flow (not sure about if its open source)

**Link to font source**
http://danross.co/flow/

**Link to font license**
❗ Found the license its inside the download folder.

License: SIL Open Font License (OFL)
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

If used in a service, software, plugin, etc. Please send me an example so I can see it in use (I’m interested). And if you feel nice, attribute http://danross.co

**Additional context**
Flow is a typeface built for ideating, presenting, wireframing.

**Comment by ayuhito** [comment]
I've DMed Dan on Twitter to get direct permission since it's somewhat unorthodoxly distributed and he may actually not want it uploaded to this repository.

**Comment by ayuhito** [comment]
I've heard no response from him. If you could contact him and get permission, we could reopen this issue then.
