### ISSUE TITLE
Font Request: 

### ISSUE THREAD

**Issue by GregBrimble** [fontsource/fontsource#220]
**Font Name**
Tiresias

**Link to font source**
https://packages.debian.org/sid/fonts-tiresias

**Link to font license**
[GPL-3+_with-font-exception](https://metadata.ftp-master.debian.org/changelogs//main/f/fonts-tiresias/fonts-tiresias_0.1-6_copyright). Is that accepted?

**Comment by ayuhito** [comment]
I don't think I can accept a GPL3 license into the repository due to its restrictions. 

It will be unusable for a lot of downstream users and isn't really a commercial friendly solution.

Thanks for the issue!
