### ISSUE TITLE
Download files directly on website

### ISSUE THREAD

**Issue by ayuhito** [fontsource/fontsource#244]
I believe that Fontsource can do more than just serve NPM packages with the new directory. Ideally, I want to serve as a modern replacement for [google-webfonts-helper](https://github.com/majodev/google-webfonts-helper), which is an amazing tool but has decayed from lack of maintenance.

One feature that could be included on the Fontsource website is the ability to download all the font files and CSS in a zip format. This could be done very easily using [JSDelivr](https://www.jsdelivr.com/) as the file host and shouldn't require much custom logic.

UI-wise, it could be similar to the NPM icon button found at the top right corner of each preview.

**Comment by jwr1** [comment]
I would be able to add this to the website if there were a source to download the zip file from. I was thinking we could just add a zip file to the root of each package with a filename of `[fontID].zip`; e.g. `packages/roboto/roboto.zip`.

**Comment by ayuhito** [comment]
Actually it might not be good for us to add to the NPM package size. It wouldn't be useful to regular NPM users who'd need to download much more. I think we might even hit NPM package size limits for our biggest fonts.

I'd also have concerns abusing JSDelivr's CDN when some of our packages already exceed their size limitations (which JSDelivr has kindly removed for us under fair use).

I was thinking we could host it on our API server instead... which is under development. We should hopefully see the first iteration of it deployed within the next month (without the zip download function)?

**Comment by ayuhito** [comment]
I've also updated this issue as an API issue, now that the initial API is officially out.

It would make sense to make the download endpoint first before addressing the website:
`GET api.fontsource.org/v1/fonts/:id/download` - Which should return a ZIP file.
