### ISSUE TITLE
Investigate Lerna alternatives

### ISSUE THREAD

**Issue by ayuhito** [fontsource/fontsource#250]
Lerna has been largely unmaintained as of lately and it's quite a regular occurrence for package publishes to break mid-build, causing a need for manual cleanup to occur afterwards.

One of the key objectives of this repository is self-sustainability. If I were to disappear for a period of time, at the bare minimum I would expect this repo to automatically update any Google Fonts. That current objective is only met *sometimes*. Of course, I'm also open to add more maintainers to secure the longevity of this project. 

I understand that publishing 1000+ packages in one build is a tall order and is an edge case - nonetheless if there is a better more reliable alternative, I'll take it.

One notable alternative I've seen is [Changesets](https://github.com/atlassian/changesets), however, I still need to look deeper into it.

If there any other suggestions to publish a large number of packages in a monorepo, please do link them below.

**Comment by ayuhito** [comment]
A part of me just wants to make our own publisher. But I also have a lot of other things going on that makes it hard to justify investing a lot of time building this.

Its main focus would aim to keep things as lean as possible and keeping everything simple. As barebones as it can be and not have any feature bloat. Designed for the sole purpose of safely publishing 1000+ packages if need be. 

It isn't supposed to replace your standard monorepo setup. It won't have an extensive feature list and it's likely many feature requests would just be denied to maintain lack of complexity. It has to be just enough to just... work without any worries.

Currently Fontsource runs into memory issues (it exceeds default Node RAM allocation and thus I always have to increase it to 10GB locally) and runs into random errors as Lerna struggles to handle the sheer number of packages. It's understandable that no one considered Fontsource into their design architecture - I already broke GitHub a couple of times through their tag system with this repo after all, which is another key requirement to not use tags to determine package differences.

Conceptually, it would be simple. Git diff an entire directory, identify packages that need to be bumped, package and publish. Nothing more.

**Comment by stevenschmatz** [comment]
Turborepo? https://turborepo.com/ cc @jaredpalmer

**Comment by ayuhito** [comment]
@stevenschmatz, thanks for the suggestion! Looking over the website's pitch, I have a feeling their focus is more on seamless integration with different toolchains rather than the simple brute requirements of mass publishing for Fontsource.

However, I've actually already started working on my own solution and so far I'm very pleased with the results for the niche requirements it has. Once ready to release in a week or so, I'll close this issue.

**Comment by jaredpalmer** [comment]
We do not plan on implementing publishing this year. We suggest changesets in the interim
