### ISSUE TITLE
Update Overpass Following Significant bugfix 

### ISSUE THREAD

**Issue by michaelfaith** [fontsource/fontsource#253]
After a two year old, significant issue was originally identified, they've finally merged the fix in: https://github.com/RedHatOfficial/Overpass/pull/84  

This issue has been a big problem for our organization.  Just requesting that @fontsource/overpass is updated with the new versions of these files.

**Comment by ayuhito** [comment]
Usually, we don't manually update Google Fonts and let it match things upstream, however, I don't think we'll run into any major issues updating this.

My only concerns are font file sizes (Google strips a lot of things through their build process compared to original) and the very small possibility Google pushes an update that still hasn't included this fix, which may revert things.

**Comment by michaelfaith** [comment]
I see.  I put in a similar request in the Google fonts github, not really knowing how that flow works. https://github.com/google/fonts/issues/3490  From your experience would it be better to wait for them to update, or are they not very on top of updates like this?  My first time having this sort of issue.

**Comment by ayuhito** [comment]
It's a slow process. There's a lot happening and your issue might get buried. I'll look into manually updating Overpass, although I'm a bit bogged down with some stuff IRL and there are some Lerna publishing bugs I need to address so you might need to wait a bit.

**Comment by michaelfaith** [comment]
Understood. I appreciate your help.

**Comment by ayuhito** [comment]
Looking at the Google Fonts issue and how it has progressed, I think it's better for us to let them resolve it upstream rather than us tinkering with it down here.

**Comment by michaelfaith** [comment]
@DecliningLotus Sounds good. I appreciate it.  Just so I understand the flow of that.  Once they do update their files and release, will fontsource automatically pull that in, without any manual intervention, or will there still need to be some kind of action?  And I guess there'd be some mention in your changelog, so I know when it's been updated?  Thanks again.

**Comment by ayuhito** [comment]
@michaelfaith, Fontsource runs a weekly actions workflow automatically. No need for any manual intervention.

Changelog wise... we don't write up changelogs for individual font updates. Only for macro updates that apply to all fonts - refer to our CHANGELOG.md for more clarification.

You would see it as an individual patch update on NPM. I would track the main Google Fonts PR to know when changes will be applied. Note Google takes a week or so from PR merge to production upload, and then Fontsource will pick it up from there.

**Comment by michaelfaith** [comment]
Thanks for the info.  This helps a ton.

**Comment by michaelfaith** [comment]
@DecliningLotus this was finally merged into production in Google's Fonts repo: https://github.com/google/fonts/pull/3832 and https://github.com/google/fonts/pull/3834.  Will these be picked up in the weekly workflow?  Or will some manual intervention be needed to absorb the updates?

**Comment by ayuhito** [comment]
@michaelfaith, we should have the latest files that Google is serving publicly? Are there differences from what Google Fonts is serving and what Fontsource is?

**Comment by michaelfaith** [comment]
The @fontsource/overpass package hasn't been updated in a few months, and there was a significant bug resolved in the font (referenced in the original post of this issue), and that's finally been absorbed by google fonts and marked as in production 4 days ago (tagged in the PRs).  So it may be too soon for your weekly workflow to have picked it up?

**Comment by ayuhito** [comment]
Ah, yes the build runs every Sunday. I've manually launched the GitHub Action now though which should hopefully update it.

But like I said before, even if they mark it for production, it still sometimes takes a while for it to actually go production live, considering the build from 2 days ago didn't pick it up.

**Comment by ayuhito** [comment]
Yup, it's still not truly updated. Gotta wait a bit more ^^

**Comment by michaelfaith** [comment]
Sounds good.  I'll keep an eye on it.  Thanks!
