### ISSUE TITLE
Font Request: STIX Two Math

### ISSUE THREAD

**Issue by marcelmusiol** [fontsource/fontsource#265]
**Font Name**
STIX Two Math

**Link to font source**
https://fonts.google.com/specimen/STIX+Two+Math

**Link to font license**
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

**Comment by ayuhito** [comment]
Stix Two Math should be published within the next couple days. I'll close this issue then.

**Comment by ayuhito** [comment]
@marcelmusiol, Stix Two Math has been published. Thanks for waiting!
