### ISSUE TITLE
Font Request: Norwestor

### ISSUE THREAD

**Issue by jeremy-blevins** [fontsource/fontsource#275]
**Font Name**
Norwestor
Ensure it is an Open Source downloadable font.

**Link to font source**

https://jamiewilson.io/norwester/

Preferably Github, however, main website is also acceptable.

**Link to font license**
SIL OFL

https://jamiewilson.io/norwester/

Accepted licenses are SIL OFL, Apache 2, MIT and Ubuntu Font License 1.0.

**Additional context**
Fontsource has been incredibly helpful. It would be helpful to be able to import Norwestor as well. 
Thanks!

**Comment by ayuhito** [comment]
Thanks for the issue @jeremy-blevins. @fontsource/norwester has been published.
