### ISSUE TITLE
Import syntax listed on website typo?

### ISSUE THREAD

**Issue by joezappie** [fontsource/fontsource#278]
**Describe the bug**
On fontsource.org the instructions for each font lists the step of:

`import "@fontsource/roboto.css"`

For me, this does not work. To get it to work I had to do either of these:

```
import "@fontsource/roboto"
import "@fontsource/roboto/latin.css"
```

I'm only familiar with the basics of webpack with css-loader, so maybe these instructions are intended for another build tool but I found this quite confusing. node_modules/@fontsource/roboto.css also isn't a real file. Is this a typo?

Clicking on the "full documentation" link, the examples there do not include the @fontsource/roboto.css notation and only the other two.

**To Reproduce**

1. Go to any font page - https://fontsource.org/fonts/roboto
2. View Quick Installation section

**Expected behavior**
Installation instruction should drop the ".css"

**Screenshots**
![image](https://user-images.githubusercontent.com/6005836/125006573-50d3f280-e013-11eb-8c47-88c1d76ee9e7.png)

**Comment by jwr1** [comment]
Yes, that does look like a typo. To import the package entry point you can use either of the following:
```js
import "@fontsource/roboto"
import "@fontsource/roboto/index.css"
```
I will work on fixing that right now.

**Comment by jwr1** [comment]
The typo is now fixed with commit https://github.com/fontsource/fontsource/commit/c29646a00fc816c9bce5e29790492700b867f0d0.
