### ISSUE TITLE
Font Request: Bagnard

### ISSUE THREAD

**Issue by Scrumplex** [fontsource/fontsource#282]
**Font Name**
Bagnard

**Link to font source**
https://github.com/sebsan/Bagnard

**Link to font license**
https://github.com/sebsan/Bagnard/blob/master/OFL.txt

**Additional context**
Featured on Open Foundry:
https://open-foundry.com/fonts/bagnard_regular

**Comment by ayuhito** [comment]
Should be published onto NPM within a couple hours. Thanks!

**Comment by Scrumplex** [comment]
> Should be published onto NPM within a couple hours. Thanks!

No no :D. Thank *you*! You did the work after all
