### ISSUE TITLE
Font fails to download

### ISSUE THREAD

**Issue by hhimanshu** [fontsource/fontsource#286]
**Describe the bug**
The font is failing to download in the browser. I am currently using v`4.5.0` for `@fontsource/poppins` font.
The package.json shows this dependency [here](https://github.com/hhimanshu/create-react-ts-starter/blob/main/package.json#L68)

**To Reproduce**
1. Go to https://react-ts-starter-hhimanshu.vercel.app/
2. Open Dev Tools
3. You will see error that says
```
Failed to decode downloaded font: <URL>
OTS parsing error: invalid sfntVersion: 1702391919
```

**Expected behavior**
The fonts should have been downloaded successfully

**Screenshots**

https://user-images.githubusercontent.com/6589036/126553684-76f6b5a5-fffd-460c-80e2-7e6fbfa486f6.mp4

**Additional context**
The GitHub repo for this is available at https://github.com/hhimanshu/create-react-ts-starter

**Comment by ayuhito** [comment]
Is this behaviour specific to `@fontsource/poppins` or other fonts too? 

If so, I would experiment with your Webpack config as that's usually the area where most developers might overlook.

**Comment by hhimanshu** [comment]
Hello @DecliningLotus, 

I tried the following fonts and they all failed

https://fontsource.org/fonts/open-sans
https://fontsource.org/fonts/abel

When you said webpack config, what specifically did you want to say? My `webpack` config is available [here](https://github.com/hhimanshu/create-react-ts-starter/blob/10e95514b41ecb20b9eac7d3a4494c242d860a46/webpack.common.js)

Thanks

**Comment by hhimanshu** [comment]
So, the issue was with updated version of `css-loader` that cause it. The relevant commit for fix is at available in my [pull request](https://github.com/hhimanshu/create-react-ts-starter/pull/36/commits/eb839011630fbd7e89fd5aa2f9c630bd5bc9ae4f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)

Thanks for the help, @DecliningLotus
