### ISSUE TITLE
Font Request: Metamorphous

### ISSUE THREAD

**Issue by alerque** [fontsource/fontsource#287]
**Font Name**
Metamorphous

**Link to font source**
https://fonts.google.com/specimen/Metamorphous?query=James+Grieshaber

**Link to font license**
OFL

**Additional context**
Or is there a way to package any arbitrary Google font without needing it to be explicitly supported?

**Comment by ayuhito** [comment]
@alerque, I think you might've missed the font: https://fontsource.org/fonts/metamorphous
Oops. :)

**Comment by alerque** [comment]
Um, yes, yes I did miss it. I must have typoed my search or something, sorry for the noise.
