### ISSUE TITLE
Font Request: 

### ISSUE THREAD

**Issue by vinclou** [fontsource/fontsource#288]
**Font Name**
Iosevka

**Link to font source**
https://github.com/be5invis/Iosevka
https://typeof.net/Iosevka/

**Link to font license**
`SIL OFL`
https://github.com/be5invis/Iosevka/blob/master/LICENSE.md

**Additional context**
A very cool old school font that would be an awesome additon here

**Comment by ayuhito** [comment]
Should be uploaded to NPM within a couple of hours!

**Comment by vinclou** [comment]
@DecliningLotus 
C|_|
`Thank you =)`
