### ISSUE TITLE
Font Request: DejaVu

### ISSUE THREAD

**Issue by ScottGuthart** [fontsource/fontsource#301]
**DejaVu**

**[Latest Release](https://github.com/dejavu-fonts/dejavu-fonts/releases/tag/version_2_37)**

**[License](https://github.com/dejavu-fonts/dejavu-fonts/blob/master/LICENSE)**

**Additional context**
It's a derivative of [Bitstream Vera](https://en.wikipedia.org/wiki/Bitstream_Vera) which is also available via OFL.

**Comment by ayuhito** [comment]
@ScottGuthart, 
 - @fontsource/dejavu-math@4.5.1
 - @fontsource/dejavu-mono@4.5.1
 - @fontsource/dejavu-sans@4.5.1
 - @fontsource/dejavu-serif@4.5.1

The above packages have been published onto NPM. Thanks!
