### ISSUE TITLE
Font Request: OpenDyslexic

### ISSUE THREAD

**Issue by bollwyvl** [fontsource/fontsource#303]
**Font Name**

- OpenDyslexic

**Link to font source**

- https://github.com/antijingoist/opendyslexic
- https://opendyslexic.org

**Link to font license**

- https://github.com/antijingoist/opendyslexic/blob/master/OFL.txt

**Additional context**

- This is among the few open source alternatives I've found for dyslexia-aware typesetting that also has a monospace form: I'm particuarly interested in the code reading/editing/annotating/review use case.

- More broadly: thanks for fontsource :heart_eyes_cat: ! I may very well be doing _yet another repacking_ for [jupyterlab-fonts](https://github.com/deathbeds/jupyterlab-fonts) and really appreciate the data-driven, license-aware effort undertaken here!

**Comment by ayuhito** [comment]
@bollwyvl, `@fontsource/opendyslexic` has been published. Thanks!

**Comment by bollwyvl** [comment]
Brilliant, thank you!
