### ISSUE TITLE
Kaisei family not published

### ISSUE THREAD

**Issue by josteph** [fontsource/fontsource#311]
It seems kaisei font family is not published

https://github.com/fontsource/fontsource/tree/main/packages/kaisei-harunoumi

And the docs is 404 as well: https://fontsource.org/fonts/kaisei-harunoumi

Is there an issue with this font family?

**Comment by ayuhito** [comment]
Fixed in [`82c412e`](https://github.com/fontsource/fontsource/commit/82c412e376eb24fc0150fb8cb9af703ad11f6b57).

Auto-publishing is currently broken, but we have a solution in the works that will soon address it. I need to publish with Lerna manually in the meantime.
