### ISSUE TITLE
Font Request: GNU Unifont

### ISSUE THREAD

**Issue by hexagonrecursion** [fontsource/fontsource#322]
**Font Name**
GNU Unifont

**Link to font source**
https://unifoundry.com/unifont/index.html

**Link to font license**
https://unifoundry.com/LICENSE.txt
Also this page https://unifoundry.com/unifont/index.html says:
> As of Unifont version 13.0.04, the fonts are dual-licensed under the SIL Open Font License (OFL) version 1.1 and the GNU GPL 2+ with the GNU font embedding exception.

**Additional context**

**Comment by ayuhito** [comment]
Interpreting the dual license statement is a bit ambiguous to me. Does that mean it's inclusive of both licenses or you can just pick and choose? (In which case why would you ever choose the GPL license)

If it's the latter, I can accept this request. If it's the former, we can't since we don't allow GPL licenses in this repo.

It might be better to get clarification from Unifoundry themselves to ensure we aren't crossing any lines here.

**Comment by hexagonrecursion** [comment]
I have sent them an email. I'll get back to you when I receive a response.

**Comment by hexagonrecursion** [comment]
Have you heard of the GNU Font Embedding Exception?

> From 	Paul Hardy
> To 	Andrey Bienkowski
> 
> I would first ask why someone would not accept the GPL with the GNU
> Font Embedding Exception.  If the repository is actively opposed to
> GNU licensing, I am not interested in spending time supporting it.
> 
> Thank you,
> 
> Paul Hardy

From: https://unifoundry.com/LICENSE.txt

> The license for the compiled fonts is covered by the above GPL terms
> with the GNU font embedding exception, as follows:
> 
>      As a special exception, if you create a document which uses this font,
>      and embed this font or unaltered portions of this font into the document,
>      this font does not by itself cause the resulting document to be covered
>      by the GNU General Public License. This exception does not however
>      invalidate any other reasons why the document might be covered by the
>      GNU General Public License. If you modify this font, you may extend
>      this exception to your version of the font, but you are not obligated
>      to do so. If you do not wish to do so, delete this exception statement
>      from your version. 
> 
> See "http://www.gnu.org/licenses/gpl-faq.html#FontException" for more details.

**Comment by ayuhito** [comment]
Alright, I guess that's good enough. Although I still have some concerns on diverging from our usual licenses.

Will look into making a PR soon.

**Comment by ayuhito** [comment]
You can find it at @fontsource/unifont now! Thanks for waiting!
