### ISSUE TITLE
Open Sans looks broken

### ISSUE THREAD

**Issue by Patta** [fontsource/fontsource#377]
Since version 4.5.1 open-sans looks broken, especially the bold (600) font weight.

v4.5.0
![image](https://user-images.githubusercontent.com/2151127/137704204-62e90dc2-3175-430d-bf7a-6e062c6b7c8e.png)

v4.5.1
![image](https://user-images.githubusercontent.com/2151127/137704289-b31bceb5-f251-4717-a298-b9806e0f1e4e.png)

**Comment by ayuhito** [comment]
Not an issue with Fontsource. Check google/fonts#3876.

Thankfully, you can choose to rollback to an older Fontsource version for the time being until they push a fix.
