### ISSUE TITLE
Fontsource Search Directory

### ISSUE THREAD

**Issue by ayuhito** [fontsource/fontsource#48]
# Search Directory

As this project has grown quite rapidly recently and isn't slowing down, I've been considering it to be appropriate for an official Fontsource search directory to be developed similar to https://google-webfonts-helper.herokuapp.com/fonts and https://fonts.google.com as we grow to be an Open Source hub for fonts NOT specific to Google.

## Data
In preparation for something like this, all packages have a `metadata.json` file that contains all sorts of useful defining information that could be read and used by the directory. Examples such as [here](https://github.com/fontsource/fontsource/blob/master/packages/roboto/metadata.json) and [here](https://github.com/fontsource/fontsource/blob/master/packages/firago/metadata.json) show that we can differentiate whether it is a Google Font or another type, etc.

Of course, if there are better solutions to this, feel free to share your thoughts about that!

## Contribution
I don't necessarily have the time to work on this project solo, however, I'd love to see if there are any others in this community who'd wish to help work on it instead! It'd be great to have a designer to initially mockup the directory to set a modern minimalistic theme before we begin development on it directly in a separate repo in this org. 

Let us know if you're interested in helping out! There are tons of technical challenges to overcome with this from the base framework we'll be utilising to controlling bandwidth. It's a bit of a large undertaking but hopefully fun to take on in the end.

**Comment by jwr1** [comment]
Hello, I was working on my own projects when I came across this repo. I noticed you needed a website to search through all the fonts, so I took the liberty to make one. I have uploaded some screenshots to show what it looks like. 
![Screenshot_2020-09-29 Fontsource Search](https://user-images.githubusercontent.com/47087725/94561009-71278300-0231-11eb-949b-6a54ba2f680e.png)
![Screenshot_2020-09-29 Fontsource Search(1)](https://user-images.githubusercontent.com/47087725/94561018-72f14680-0231-11eb-893a-39db2395e700.png)
I can upload the code wherever you would like.

**Comment by jwr1** [comment]
Here is a [Demo](https://jwr12135.github.io/fontsource-search) for the website, and here is the [source code](https://github.com/jwr12135/fontsource-search/).

**Comment by ayuhito** [comment]
Hey @jwr12135, that looks amazing! Thank you for contributing to the project! 

How would you like to handle the main publication of this? Would you want to transfer the repo to the Fontsource org or did you have any other ideas?

**Comment by jwr1** [comment]
Transfering the repository to the Fontsource organization works for me. I don't mind either way. I'm just glad to help out.

**Comment by ayuhito** [comment]
Feel free to transfer the repo over to the Fontsource org and I'll handle the rest. Once again, appreciate the contribution!

**Comment by jwr1** [comment]
Github says I need permission to create public repositories in the fontsource organization before I can transfer it.

**Comment by ayuhito** [comment]
@jwr12135, sent you an invite to the org which should give you the relevant perms. :)

**Comment by jwr1** [comment]
Alright, the repository has been transferred. Also, if possible, I would like to keep permissions for the repo in case I want to work on it further. Thanks for the help. :)

**Comment by ayuhito** [comment]
Absolutely! Feel free to remain as a member of the Fontsource org and contribute wherever you can! I'll be looking into updating the main repo documentation to link the directory when I'm free. 

Closing this issue now. Thank you!
