### ISSUE TITLE
Font Flickering on First load in Next js with Fountsource and Material Ui?

### ISSUE THREAD

**Issue by siamahnaf** [fontsource/fontsource#496]
I am building one `Next.js` applications. For styling I am using `Material-ui`. I am using [`Inter`](https://fontsource.org/fonts/inter) font from FontSource.

I am facing one flickering problem in this site-
![ice_video_20220517-214806_edit_0](https://user-images.githubusercontent.com/78312010/168857452-5fda27a2-eeb6-4af5-ac26-73c849ede350.gif)

I can't understand why I am seeing this type of flicker?

This is the live url- https://hardjourney.vercel.app/login

Here is my code example-

I install `@fontsource/inter` this and just call it in my `_app.tsx`-

```
//Fonts
import "@fontsource/inter/300.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
```

And then I add this in `Material-ui` theme-

```
const theme = createTheme({
    typography: {
        fontFamily: "Inter"
    }
});
export default theme;
```

Font working but problem it the site load first time without font and then load fonts. What is the problem Where I have to change in my applications. Please help me.

**Comment by mxxjng** [comment]
Setting the font-display to auto helped in my case

**Comment by ayuhito** [comment]
Yeah it's the default behaviour of the `font-display` property. We can only ship one as the default, and Google Lighthouse prefers the `swap` behaviour which gives you the FOUT behaviour. Personally, I'm a big fan of using the `optional` option.

We're working on ways to generate custom CSS that'll let you modify the `font-display` property, but at the moment you'll either have to use the Sass mixins, use a hacky build step to copy the font files into your public dir and write your own font-face CSS, or just manually download the font/use Google Fonts.

**Comment by NeversSync** [comment]
@ayuhito Any updates on the ability to the modify the default `font-display` property?

**Comment by ayuhito** [comment]
> Any updates on the ability to the modify the default `font-display` property?

Finishing #520 would enable #234 to be resolved quickly. That would be a possible solution.

We're also still on the mock-up stage for a new website (finally secured a designer!). One of the features of the new website is being able to just download the files directly and host it yourself with all the necessary CSS files.

Both solutions will free up opportunities to move away from bundlers and let developers do whatever they want, whether it is preloading or making edits to the CSS defaults.

I'm just really busy so progress is slow, but we'll get there eventually.

**Comment by nekmart** [comment]
> Setting the font-display to auto helped in my case

Hello, Where I use Font Display auto?

**Comment by siamahnaf** [comment]
Any solutions? How long time we should wait for getting the solutions.

**Comment by ayuhito** [comment]
No ETA. PRs are welcome if you want to help speed things up 🙂

**Comment by ayuhito** [comment]
You can now use [CSS variables](https://fontsource.org/docs/getting-started/display) to change `font-display` in v5! 🎉

**Comment by slnsrn** [comment]
https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

```js
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap', // this worked for me 👍 
})
