### ISSUE TITLE
Thank-you!

### ISSUE THREAD

**Issue by ehowey** [fontsource/fontsource#50]
Hey @DecliningLotus - I just wanted to say this is a great resource and thank-you for the work on it.  I have noticed the problems with typeface that you have also noted. Thanks for the work into this.  Feel free to close this issue once you see it.  Just wanted to note the effort you have put into this!

I am using it on my project [gatsby-theme-catalyst](https://github.com/ehowey/gatsby-theme-catalyst) now for one theme and will transition some of the other fonts/projects I have to this.

Keep it up!

**Comment by ayuhito** [comment]
Appreciate the support @ehowey. glad you find use in this project! Let me know if you ever have any issues with it. :)
