### ISSUE TITLE
Montserrat tabular figures not working

### ISSUE THREAD

**Issue by marceloverdijk** [fontsource/fontsource#59]
**Describe the bug**
I'm trying to use Montserrat with tabular figures (`font-variant-numeric: tabular-nums`) but it does not seem to work.
According to https://github.com/JulietaUla/Montserrat/issues/101 this should be supported in the Montserrat font.

**To Reproduce**

1. Go to https://jsfiddle.net/marceloverdijk/mvwg8Lnj/
2. Click on Run

**Expected behavior**
Second table should have tabular nums (so every num uses the same width) but does not have it.

**Screenshots**
![image](https://user-images.githubusercontent.com/197004/91609652-17a10f80-e978-11ea-8215-f853256fb7d9.png)

**Additional context**
I also used my local installed Montserrat font in the `@fontface` definition like:
```
  src:
    local('Montserrat Regular '),
    local('Montserrat-Regular'),
```
and it that case it does work.

![image](https://user-images.githubusercontent.com/197004/91609802-5e8f0500-e978-11ea-8b4c-6395b157715b.png)

Not sure if this is a bug for fontsource.
What source is fontsource using for this font? I understand e.g. Google Font also does not support the tabular figures.

**Comment by ayuhito** [comment]
@marceloverdijk, I think a similar issue was discussed in #39. We pull our fonts directly from Google and use their stripped out version to cut down on file sizes, which works for the majority of developers utilising Fontsource.

Do you disagree with the explanations in #39 or do you have a solution for the issues stated?

**Comment by marceloverdijk** [comment]
Thx this explains it. I prob will end up copying the source files to my project and not using NPM.
