### ISSUE TITLE
Include SASS/SCSS files in output packages

### ISSUE THREAD

**Issue by jacobq** [fontsource/fontsource#74]
Similar to https://github.com/fontsource/fontsource/issues/64

**Is your feature request related to a problem? Please describe.**
I am currently using [`roboto-fontface`](https://www.npmjs.com/package/roboto-fontface) and would like to replace it with `fontsource-roboto` (+ `fontsource-roboto-condensed`, & `fontsource-roboto-slab`). However, the fontsource packages don't include SCSS files for easy inclusion into my project (though it's not terribly hard to work around).

**Describe the solution you'd like**
I would like to able to do something like this:

```scss
$roboto-font-path: './fonts'; /* if there're paths or parameters to be customized */
@import 'fontsource-roboto'; /* or @use */
```

**Describe alternatives you've considered**
I actually haven't thought much about this and am not a CSS expert by any means. It just seems like some of the benefits of using pre-processors are probably going to waste. What I currently do to make this work is:

1. `@import 'fonts/foo/index.css';` (often needing to replace index with `700.css` or `all-700.css` or duplicate to get additional weights, etc.)  in my app's SCSS
2. Copy files from `node_modules/fontsource-foo/...` into my app's assets folder under `fonts/foo`

**Comment by ayuhito** [comment]
Hey @jacobq! Appreciate the issue. However, I think I'll close and mark this as a duplicate since #64 addresses all the concerns you have and outlines a proper spec to approach this.

Thanks!
