### ISSUE TITLE
Usage with Webpack + CSS + PostCSS (No SASS)

### ISSUE THREAD

**Issue by juanca** [fontsource/fontsource#77]
**Is your feature request related to a problem? Please describe.**

I have a project that does not use SASS. Instead, we prefer to use CSS with PostCSS. I think this is a really cool project that has been missing in my arsenal of frontend development. However, there is no clear guide on how to use this package with PostCSS. 

**Describe the solution you'd like**

Here is my best attempt at integrating this package into a Webpack + CSS + PostCSS project:

## Requirements

- wepback
- style-loader
- css-loader
- postcss@8.1.3
- postcss-loader@4.0.4
- postcss-import@13.0.0
- postcss-url@10.0.0

Note: I added postcss* versions because the version matching is pretty fragile. 

## webpack.config.js

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader', options: { importLoaders: 1, modules: true } },
          { loader: 'postcss-loader' },
        ],
      },
    ],
  },
};
```

## postcss.config.js

```js
module.exports = {
  plugins: [
    'postcss-import',
    ['postcss-url', { url: 'inline' }],
  ],
};
```

This particular solution will inline the fonts with the CSS payload. There is a way to extract the CSS + fonts into their own files but that is beyond the scope of _this_ guide.

## some.css

```css
@import "fontsource-open-sans/400.css";
@import "fontsource-open-sans/600.css";

:root {
  --font-family: 'Open Sans', sans-serif;
}
```

**Describe alternatives you've considered**

Another helpful guide would be to extract the CSS and/or fonts into their own asset with Webpack.

**Comment by ayuhito** [comment]
Just out of curiosity, aren't you able to use css-loader in Webpack to just import the Fontsource CSS into your project? Or is that not an option?

I'm not a hundred percent sure what's the best way to import with PostCSS otherwise, considering we need to bundle the font files too. I'd love some additional community input on that if it really is a necessary guide to have.

**Comment by juanca** [comment]
> Just out of curiosity, aren't you able to use css-loader in Webpack to just import the Fontsource CSS into your project? Or is that not an option?

I may have misconfigured my css-loader: 

AFAIK, css-loader parses `@import` expressions as relative files. So an `@import fontsource-open-sans/400.css` resolves to `Unable to import file "./fontsource-open-sans/400.css" from "some/css/file.css"`.

I used `postcss-import` to "inline" the `@import`ed file. 

Then I needed something to parse the `url(...)` files -- `postcss-url`. 

Then I needed to determine whether I wanted to bundle the fonts with my CSS payload or extract them as separate files. The easiest was to inline the woff/woff2 files as base64 encoded strings.

**Comment by ayuhito** [comment]
I don't see why you're importing through CSS when you could import it via your web/page components instead as per the main instructions shown on the readme?

That way, Webpack can handle all the file bundling and whatnot without PostCSS through css-loader.

**Comment by juanca** [comment]
That is true. 

This is all based on my opinion that my CSS should be encapsulated in the CSS files -- very similar to how the README has "SASS support". 

If we think it's better to import the font via JS then we can close this. Though, I find it weird to also support loading through SASS.

If we think it's okay to support loading through CSS then we can continue digging through this. I realized my PostCSS guide might be outdated. It looks like `css-loader` should be able to recursively manage `@import` statements. I am still digging around for the "optimal setup" -- more to come!

**Comment by ayuhito** [comment]
We support SASS out of coincidence and never had to add any additional code for it.

I'm fine with leaving this issue open to see alternatives! I fully intend Fontsource to be as flexible and accessible as possible to all developers and I'm sure there may be other similarly minded developers as you.

I'll need to start considering editing [search-directory](https://github.com/fontsource/search-directory) to have a dedicated documentation section to accommodate the expanding installation methods (especially with SASS soon to be overhauled). The README might be getting too long.

**Comment by juanca** [comment]
After much investigation, 

> I don't see why you're importing through CSS when you could import it via your web/page components instead as per the main instructions shown on the readme?
>
> That way, Webpack can handle all the file bundling and whatnot without PostCSS through css-loader.

is the way to go (as the current state of Webpack + CSS processing).

Aside for future readers: `@import` statements are not treated as idempotent modules (like JS modules) because they are technically "not pure". You will want to use a JS file and manage your application-level CSS manually.
