### ISSUE TITLE
[Google Fonts] Add Montserrat

### ISSUE THREAD

**Issue by hassankhan** [fontsource/fontsource#78]
**Font Name**
Montserrat

**Link to font source**
https://fonts.google.com/specimen/Montserrat?query=montserrat

**Link to font license**
[Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)

**Comment by ayuhito** [comment]
Is this not what you are looking for?

https://www.npmjs.com/package/fontsource-montserrat

**Comment by hassankhan** [comment]
It is indeed - apologies for the noise. I must've misspelt the name when searching for it
