### ISSUE TITLE
Font Request: FG Virgil

### ISSUE THREAD

**Issue by netcoding87** [fontsource/fontsource#82]
**Font Name**
FG Virgil

**Link to font source**
http://www.eaglefonts.com/fg-virgil-ttf-131249.htm

**Link to font license**
Unknown, but hopefully acceptable for this repo

**Additional context**
Font is used by great [excalidraw ](https://excalidraw.com/) app :)

**Comment by ayuhito** [comment]
"FG Virgil is a trademark of Jason fonted by Font Garden
Licence.

For personal use only."

We only accept Open Source Fonts here. Unfortunately, I'll have to deny this request.

Thanks for creating the issue!
