### ISSUE TITLE
Font Request: Aileron

### ISSUE THREAD

**Issue by Flawe** [fontsource/fontsource#93]
**Font Name**
Aileron

**Link to font source**
https://github.com/reinhart1010/aileron

**Link to font license**
https://github.com/reinhart1010/aileron/blob/master/LICENSE

**Additional context**
Aileron was part of [typeface](https://github.com/KyleAMathews/typefaces/tree/master/packages/aileron), would be nice to get it here so we can migrate.

**Comment by ayuhito** [comment]
Resolved in #98.
