### ISSUE TITLE
Font Request: Manrope

### ISSUE THREAD

**Issue by hawyar** [fontsource/fontsource#97]
**Font Name**
Manrope

**Link to font source**
https://github.com/sharanda/manrope

**Link to font license**
https://github.com/sharanda/manrope/blob/master/OFL.txt

**Comment by ayuhito** [comment]
Manrope is part of the [Google Fonts](https://fonts.google.com/specimen/Manrope) family and already exists as a [Fontsource package](https://www.npmjs.com/package/fontsource-manrope).
